### ISSUE TITLE
Project init fails while installing air

### ISSUE THREAD

**Issue by abhiroopc84** [beavermoney/beavermoney#66]
The module declaration for air has changed from `github.com/cosmtrek/air` to `github.com/air-verse/air`, which is causing an error while running `just init`.

```
go: github.com/cosmtrek/air@latest: version constraints conflict:
        github.com/cosmtrek/air@v1.60.0: parsing go.mod:
        module declares its path as: github.com/air-verse/air
                but was required as: github.com/cosmtrek/air
error: Recipe `init` failed on line 25 with exit code 1
```

**Comment by itsjoeoui** [comment]
Hey @abhiroopc84 , sorry I forgot to mention, you should use the `joey/fij-60-add-accounts` branch which is the most up to date as of now! This issue should have been already fixed :)
